version: '1.0'

services:

  fastapi:
    build: ./
    port:
      - "8000:8000"
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    entrypoint: /bin/sh -c "/ngrok-entrypoint.sh"
    volumes:
      - ./ngrok-entrypoint.sh:/ngrok-entrypoint.sh:ro
      - ./ngrok.yml:/etc/ngrok.yml
    env_file:
      - .env
    ports:
      - 4040:4040

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
